"""add upload status table

Revision ID: b066d6baa193
Revises: beb2ac6d325d
Create Date: 2024-06-24 16:47:53.815359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b066d6baa193'
down_revision: Union[str, None] = 'beb2ac6d325d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadstatus',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('pdf_uploaded', sa.Boolean(), nullable=False),
    sa.Column('bbox_detected', sa.Boolean(), nullable=False),
    sa.Column('metadata_parsed', sa.Boolean(), nullable=False),
    sa.Column('images_uploaded', sa.Boolean(), nullable=False),
    sa.Column('metadata_stored', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploadstatus')
    # ### end Alembic commands ###
