"""fix timezone in upload status table

Revision ID: bbbbb7cfa9f0
Revises: b066d6baa193
Create Date: 2024-06-24 16:54:20.902869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bbbbb7cfa9f0'
down_revision: Union[str, None] = 'b066d6baa193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
