services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db
  