services:
  postgres:
    container_name: yoso-db
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password