version: '3.8'
services:
  server:
    build:
      context: .
    image: yxxjimin/yoso-server
    env_file:
      - .env
    ports:
      - 80:80
  graph:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    ports:
      - 5432:5432