"""add filename column

Revision ID: 5835f0bcf6ca
Revises: c37f7cc386d0
Create Date: 2024-08-20 11:49:48.235884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5835f0bcf6ca'
down_revision: Union[str, None] = 'c37f7cc386d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_status', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_status', 'filename')
    # ### end Alembic commands ###
