"""add upload status

Revision ID: c37f7cc386d0
Revises: 033f5b59a33a
Create Date: 2024-08-20 11:47:34.063634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c37f7cc386d0'
down_revision: Union[str, None] = '033f5b59a33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_status',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('pdf_upload', sa.Boolean(), nullable=False),
    sa.Column('document_layout', sa.Boolean(), nullable=False),
    sa.Column('reading_order', sa.Boolean(), nullable=False),
    sa.Column('db_loaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_status')
    # ### end Alembic commands ###
